#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/local/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/local/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/baran/Desktop/git-repos/LFPy/examples/neuron_models/L1_NGC-DA_bNAC219_1/x86_64/.libs/libnrnmech.so" "$@"
